# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 716ce962e1732dda84183573cc737a849412bfac7d259ccb13af191a0f2d07fa471c210b9676eba4732e9443ee6793a1d88a3b2cce08821d5c69c23949392816

test:
  secret_key_base: b10a03b827b3b229db7f25758d135426e4d2bd31648d2b9cb655a09d1f13e5cccb91b6bac9452f7f51f0604df654560ca0b921afff61bf4a00a0b8f2e8cac237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
